name: movies_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.2+1
  either_dart: ^1.0.0
  equatable: ^2.0.0
  retrofit: ^4.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5
  json_annotation: ^4.8.1
  collection: 1.18.0  #https://pub.dev/packages/collection
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  pretty_dio_logger: ^1.3.1
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  bloc_test: ^9.1.7
  json_serializable: ^6.7.1
  retrofit_generator: 8.1.0
  hive_generator: 2.0.1
  mocktail: 0.3.0 #https://pub.dev/packages/mocktail
  mockito: 5.4.1 #https://pub.dev/packages/mockito


flutter:
  uses-material-design: true